"""updated_stock_uniqueness

Revision ID: 050ccce84f79
Revises: d8f2e0218a4b
Create Date: 2026-07-03 10:52:17.448084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050ccce84f79'
down_revision: Union[str, Sequence[str], None] = 'd8f2e0218a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'all_nse_stocks', ['isin_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'all_nse_stocks', type_='unique')
    # ### end Alembic commands ###
