"""check-update-1

Revision ID: c6c9a28ddbd9
Revises: 
Create Date: 2026-07-04 08:59:38.426507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c9a28ddbd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_nse_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date_of_listing', sa.DateTime(), nullable=False),
    sa.Column('isin_number', sa.String(length=20), nullable=False),
    sa.Column('face_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin_number'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('analyst_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_nse_stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('strong_sell', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_nse_stock_id'], ['all_nse_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watched_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_stock_isin', sa.String(length=20), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master_stock_isin'], ['all_nse_stocks.isin_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('accuracy_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('price_at_analysis', sa.Float(), nullable=True),
    sa.Column('price_next_day', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_theme', sa.Text(), nullable=True),
    sa.Column('buzz_level', sa.String(length=10), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=True),
    sa.Column('reddit_score', sa.Float(), nullable=True),
    sa.Column('news_score', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.Text(), nullable=True),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_analytics_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_time', sa.DateTime(), nullable=True),
    sa.Column('marketCap', sa.BigInteger(), nullable=True),
    sa.Column('trailingPE', sa.Float(), nullable=True),
    sa.Column('priceToBook', sa.Float(), nullable=True),
    sa.Column('fiftyDayAverage', sa.Float(), nullable=True),
    sa.Column('twoHundredDayAverage', sa.Float(), nullable=True),
    sa.Column('currentPrice', sa.Float(), nullable=True),
    sa.Column('high52Week', sa.Float(), nullable=True),
    sa.Column('low52Week', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yf_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yf_summaries')
    op.drop_table('stocks_analytics_info')
    op.drop_table('stock_history')
    op.drop_table('sentiment_results')
    op.drop_table('reddit_posts')
    op.drop_table('news_articles')
    op.drop_table('agent_results')
    op.drop_table('accuracy_tracking')
    op.drop_table('watched_stocks')
    op.drop_table('analyst_recommendations')
    op.drop_table('all_nse_stocks')
    # ### end Alembic commands ###
