"""nse auto gather data

Revision ID: d8f2e0218a4b
Revises: e3f3482bd113
Create Date: 2026-06-30 12:42:50.758385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f2e0218a4b'
down_revision: Union[str, Sequence[str], None] = 'e3f3482bd113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'all_nse_stocks', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'all_nse_stocks', type_='unique')
    # ### end Alembic commands ###
