"""new_added

Revision ID: e3f3482bd113
Revises: 1cf778c72740
Create Date: 2026-06-30 01:59:30.542493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f3482bd113'
down_revision: Union[str, Sequence[str], None] = '1cf778c72740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_nse_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date_of_listing', sa.DateTime(), nullable=False),
    sa.Column('isin_number', sa.String(length=20), nullable=False),
    sa.Column('face_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyst_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_nse_stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('strong_sell', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_nse_stock_id'], ['all_nse_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('close', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('dividends', sa.Integer(), nullable=True),
    sa.Column('stock_splits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_analytics_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('dividend_yield', sa.Integer(), nullable=True),
    sa.Column('dividend_rate', sa.Integer(), nullable=True),
    sa.Column('dividend_time', sa.DateTime(), nullable=True),
    sa.Column('marketCap', sa.Integer(), nullable=True),
    sa.Column('trailingPE', sa.Integer(), nullable=True),
    sa.Column('priceToBook', sa.Integer(), nullable=True),
    sa.Column('fiftyTwoWeekHigh', sa.Integer(), nullable=True),
    sa.Column('fiftyTwoWeekLow', sa.Integer(), nullable=True),
    sa.Column('fiftyDayAverage', sa.Integer(), nullable=True),
    sa.Column('twoHundredDayAverage', sa.Integer(), nullable=True),
    sa.Column('currentPrice', sa.Integer(), nullable=True),
    sa.Column('high52Week', sa.Integer(), nullable=True),
    sa.Column('low52Week', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Integer(), nullable=True),
    sa.Column('median', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yf_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['watched_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('watched_stocks', sa.Column('master_stock_id', sa.Integer(), nullable=True))
    op.add_column('watched_stocks', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'watched_stocks', 'all_nse_stocks', ['master_stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watched_stocks', type_='foreignkey')
    op.drop_column('watched_stocks', 'active')
    op.drop_column('watched_stocks', 'master_stock_id')
    op.drop_table('yf_summaries')
    op.drop_table('stocks_analytics_info')
    op.drop_table('stock_history')
    op.drop_table('analyst_recommendations')
    op.drop_table('all_nse_stocks')
    # ### end Alembic commands ###
