"""table updated

Revision ID: fcc507e0f3c1
Revises: 050ccce84f79
Create Date: 2026-07-03 16:22:46.097669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc507e0f3c1'
down_revision: Union[str, Sequence[str], None] = '050ccce84f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks_analytics_info', 'marketCap',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'trailingPE',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'priceToBook',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'high52Week',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'low52Week',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'fiftyDayAverage',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'twoHundredDayAverage',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'currentPrice',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'mean',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'median',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('stocks_analytics_info', 'fiftyTwoWeekHigh')
    op.drop_column('stocks_analytics_info', 'fiftyTwoWeekLow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks_analytics_info', sa.Column('fiftyTwoWeekLow', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stocks_analytics_info', sa.Column('fiftyTwoWeekHigh', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('stocks_analytics_info', 'median',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'mean',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'currentPrice',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'twoHundredDayAverage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'fiftyDayAverage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'low52Week',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'high52Week',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'priceToBook',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'trailingPE',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('stocks_analytics_info', 'marketCap',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
